url: http://ibmstreams.github.io/tutorials/
baseurl: /tutorials
github_editme_path: IBMStreams/tutorials/blob/gh-pages

# Site settings
title: IBM Streams Tutorials
description: "IBM Streams Tutorials"

# Build settings
markdown: kramdown
permalink: pretty
detach:  false
port:    4000
host:    127.0.0.1
